### PR TITLE
Fix out of bounds error in strace.go

### LINKED ISSUE #347: unlinkat check fails for php-alchemist/core-files @ v1.0.0 during install
Trace:
```
goroutine 1 [running]:
github.com/ossf/package-analysis/internal/strace.(*Result).parseSyscall(0xc0002f6018, 0xc00467521e, 0x8, 0xc004675227, 0x58, 0x5, 0x0)
	/src/internal/strace/strace.go:253 +0x2737
github.com/ossf/package-analysis/internal/strace.Parse(0x196f820, 0xc000010028, 0xc000010028, 0x196f820, 0xc000010028)
	/src/internal/strace/strace.go:281 +0x296
github.com/ossf/package-analysis/internal/analysis.Run(0x1986000, 0xc002a076e0, 0xc002a07800, 0x5, 0x6, 0x0, 0x0, 0x0)
	/src/internal/analysis/analysis.go:134 +0x6b0
main.handleMessage(0x19932a0, 0xc000042030, 0xc002a07680, 0xc0008523c0, 0xc00004601e, 0x22, 0xc00004a0b7, 0x6, 0x0, 0x0)
	/src/cmd/worker/main.go:136 +0x189e
main.messageLoop(0x19932a0, 0xc000042030, 0xc00004401f, 0x40, 0xc00003e06f, 0x23, 0xc00004601e, 0x22, 0xc00004a0b7, 0x6, ...)
	/src/cmd/worker/main.go:217 +0x1a9
main.main()
	/src/cmd/worker/main.go:242 +0x774
```

Raw log entry:
```
{
  "textPayload": "panic: runtime error: index out of range [1] with length 0\n\ngoroutine 1 [running]:\ngithub.com/ossf/package-analysis/internal/strace.(*Result).parseSyscall(0xc0002f6018, 0xc00467521e, 0x8, 0xc004675227, 0x58, 0x5, 0x0)\n\t/src/internal/strace/strace.go:253 +0x2737\ngithub.com/ossf/package-analysis/internal/strace.Parse(0x196f820, 0xc000010028, 0xc000010028, 0x196f820, 0xc000010028)\n\t/src/internal/strace/strace.go:281 +0x296\ngithub.com/ossf/package-analysis/internal/analysis.Run(0x1986000, 0xc002a076e0, 0xc002a07800, 0x5, 0x6, 0x0, 0x0, 0x0)\n\t/src/internal/analysis/analysis.go:134 +0x6b0\nmain.handleMessage(0x19932a0, 0xc000042030, 0xc002a07680, 0xc0008523c0, 0xc00004601e, 0x22, 0xc00004a0b7, 0x6, 0x0, 0x0)\n\t/src/cmd/worker/main.go:136 +0x189e\nmain.messageLoop(0x19932a0, 0xc000042030, 0xc00004401f, 0x40, 0xc00003e06f, 0x23, 0xc00004601e, 0x22, 0xc00004a0b7, 0x6, ...)\n\t/src/cmd/worker/main.go:217 +0x1a9\nmain.main()\n\t/src/cmd/worker/main.go:242 +0x774\n",
  "insertId": "xy5fksrl3sdvybna",
  "resource": {
    "type": "k8s_container",
    "labels": {
      "project_id": "ossf-malware-analysis",
      "container_name": "worker",
      "location": "us-central1-c",
      "pod_name": "workers-set-167",
      "namespace_name": "default",
      "cluster_name": "analysis-cluster"
    }
  },
  "timestamp": "2022-09-07T21:51:27.984036116Z",
  "severity": "ERROR",
  "labels": {
    "k8s-pod/controller-revision-hash": "workers-set-85fd5df7c",
    "k8s-pod/statefulset_kubernetes_io/pod-name": "workers-set-167",
    "k8s-pod/app": "workers",
    "compute.googleapis.com/resource_name": "gke-analysis-cluster-default-pool-d94f0570-sh9v"
  },
  "logName": "projects/ossf-malware-analysis/logs/stderr",
  "receiveTimestamp": "2022-09-07T21:51:35.835193139Z"
}
```

### PR DESCRIPTION
**Pull request by maxfisher-g**
Fixes #347

### CODE REVIEW

File: internal/strace/strace.go [hunk 1]
```diff
@@ -40,7 +40,8 @@ var (
 	unlinkPatten = regexp.MustCompile(`0x[a-f\d]+ ([^)]+)`)
 
 	// unlinkat(0x4 /tmp/pip-pip-egg-info-ng4_5gp_/temps.egg-info, 0x7fe0031c9a10 top_level.txt, 0x0)
-	unlinkatPattern = regexp.MustCompile(`0x[a-f\d]+ ([^,]+), 0x[a-f\d]+ ([^,]+), 0x[a-f\d]+`)
+	// unlinkat(AT_FDCWD /app, 0x5569a7e83380 /app/vendor/composer/e06632ca, 0x200)
+	unlinkatPattern = regexp.MustCompile(`\S+ ([^,]+), 0x[a-f\d]+ ([^,]+), 0x[a-f\d]+`)
```
Comment (oliverchang) [inline internal/strace/strace.go:44]: nit: can you use `[^\s]+` instead of `\S+` for consistency with the other regexes in this file?

**Review by oliverchang — APPROVED** [review]

File: internal/strace/strace_test.go [hunk 2]
```diff
@@ -202,6 +202,14 @@ func TestParseFilesOneEntry(t *testing.T) {
 				Delete: true,
 			},
 		},
+		{
+			name:  "unlinkat_2",
+			input: "I0907 23:56:32.113900     302 strace.go:631] [  48:  48] rm X unlinkat(AT_FDCWD /app, 0x5569a7e83380 /app/vendor/composer/e06632ca, 0x200) = 0 (0x0) (69.951µs)",
+			want: strace.FileInfo{
+				Path:   "/app/vendor/composor/e06632ca",
```
Comment (calebbrown) [inline internal/strace/strace_test.go:209]: This should be `composer` not `composor`

**Comment by oliverchang** [comment]
> Was there any reason for preferring `[^\s]` over `\S` initially in the regexes?

Nope. Feel free to send a separate PR to change all of these if you prefer \S.

**Review by calebbrown — APPROVED** [review]
