### PR TITLE
Fix analysis script error when /var/lib is backed by an overlay mount

### LINKED ISSUE #689: Sandbox failed (error starting container: exit status 125)
I have error with default installation

### Command

```scripts/run_analysis.sh -ecosystem pypi -package Django```

```root ➜ /workspaces/package-analysis (main) $ scripts/run_analysis.sh -ecosystem pypi -package Django
-----------------------------------------
Package Details
Ecosystem:                pypi
Package:                  Django
Version:                  
Location:                 remote
-----------------------------------------
Analysing package

2023-03-13T10:57:57.754Z        INFO    worker/logging.go:63    Got request     {"ecosystem": "pypi", "name": "Django", "version": "", "package_path": "", "results_bucket_override": ""}
2023-03-13T10:57:57.786Z        INFO    analyze/main.go:199     Starting static analysis
2023-03-13T10:57:57.786Z        DEBUG   sandbox/init.go:71      Creating bridge network
2023-03-13T10:57:57.794Z        DEBUG   sandbox/init.go:31      Loading iptable rules
2023-03-13T10:57:57.797Z        INFO    worker/runstatic.go:35  Running static analysis {"tasks": ["all"]}
2023-03-13T10:57:57.797Z        DEBUG   sandbox/sandbox.go:240  podman  {"args": ["--cgroup-manager=cgroupfs", "--events-backend=file", "pull", "gcr.io/ossf-malware-analysis/static-analysis:latest"]}
2023-03-13T10:57:58.730Z        DEBUG   sandbox/sandbox.go:240  podman  {"args": ["--cgroup-manager=cgroupfs", "--events-backend=file", "image", "prune", "-f"]}
2023-03-13T10:57:58.860Z        DEBUG   sandbox/sandbox.go:240  podman  {"args": ["--cgroup-manager=cgroupfs", "--events-backend=file", "create", "--runtime=/usr/local/bin/runsc_compat.sh", "--init", "--dns=8.8.8.8", "--dns=8.8.4.4", "--dns-search=.", "--network=analysis-net", "-v", "/results.json:/results.json", "gcr.io/ossf-malware-analysis/static-analysis:latest"]}
2023-03-13T10:57:59.194Z        DEBUG   sandbox/sandbox.go:240  podman  {"args": ["--cgroup-manager=cgroupfs", "--events-backend=file", "start", "--runtime=/usr/local/bin/runsc_compat.sh", "--runtime-flag=root=/var/run/runsc", "--runtime-flag=debug-log=/tmp/sandbox_logs_3054061372/runsc.log.%COMMAND%", "2eba113554b38dbf232e29d446f3e7c18cfd2831ca721daf37e20143649610d3"]}
2023-03-13T10:57:59.258Z        WARN    log/writer.go:63        time="2023-03-13T10:57:59Z" level=warning msg="Couldn't run auplink before unmount /var/lib/containers/storage/aufs/mnt/d1d267d24ebbf46d29baa0a5a8eec260674db6b43604655a7595aa5d63e5391b: exec: \"auplink\": executable file not found in $PATH"    {"args": ["/usr/local/bin/staticanalyze", "-ecosystem", "pypi", "-package", "django", "-version", "4.1.7", "-analyses", "all", "-output", "/results.json"]}
github.com/ossf/package-analysis/internal/log.WriteTo
        /src/internal/log/writer.go:63
github.com/ossf/package-analysis/internal/log.Writer.func1
        /src/internal/log/writer.go:40
2023-03-13T10:57:59.449Z        WARN    log/writer.go:63        Error: unable to start container "2eba113554b38dbf232e29d446f3e7c18cfd2831ca721daf37e20143649610d3": error mounting storage for container 2eba113554b38dbf232e29d446f3e7c18cfd2831ca721daf37e20143649610d3: error creating aufs mount to /var/lib/containers/storage/aufs/mnt/d1d267d24ebbf46d29baa0a5a8eec260674db6b43604655a7595aa5d63e5391b: invalid argument    {"args": ["/usr/local/bin/staticanalyze", "-ecosystem", "pypi", "-package", "django", "-version", "4.1.7", "-analyses", "all", "-output", "/results.json"]}
github.com/ossf/package-analysis/internal/log.WriteTo
        /src/internal/log/writer.go:63
github.com/ossf/package-analysis/internal/log.Writer.func1
        /src/internal/log/writer.go:40
2023-03-13T10:57:59.451Z        DEBUG   sandbox/sandbox.go:240  podman  {"args": ["--cgroup-manager=cgroupfs", "--events-backend=file", "stop", "-t=5", "-i", "2eba113554b38dbf232e29d446f3e7c18cfd2831ca721daf37e20143649610d3"]}
2023-03-13T10:57:59.581Z        DEBUG   sandbox/sandbox.go:240  podman  {"args": ["--cgroup-manager=cgroupfs", "--events-backend=file", "rm", "--all", "--force"]}
2023-03-13T10:57:59.914Z        FATAL   analyze/main.go:128     Static analysis aborted {"error": "sandbox failed (error starting container: exit status 125)"}
main.staticAnalysis
        /src/cmd/analyze/main.go:128
main.main
        /src/cmd/analyze/main.go:200
runtime.main
        /usr/local/go/src/runtime/proc.go:250

-----------------------------------------
Analysis failed

docker process exited with code 1

Ecosystem:                pypi
Package:                  Django
Version:                  
Location:                 remote
-----------------------------------------```

### PR DESCRIPTION
**Pull request by maxfisher-g**
Add check to the analysis script to ensure analysis image mounts an appropriate directory to `/var/lib/containers` inside the analysis image that is not backed by a non-overlay filesystem. For Github Codespaces, automatically falls back to using a temp directory, and for other environments, a manual override is requested.

Fixes #689

### CODE REVIEW

**Review by oliverchang — APPROVED** [review]
thanks!

File: scripts/run_analysis.sh [hunk 1]
```diff
@@ -115,7 +115,39 @@ fi
...
+
+CONTAINER_MOUNT_DIR="/var/lib/containers"
+
+if [[ -n "$CONTAINER_DIR_OVERRIDE" ]]; then
+	CONTAINER_MOUNT_DIR="$CONTAINER_DIR_OVERRIDE"
+elif [[ $CODESPACES == "true" ]]; then
+	CONTAINER_MOUNT_DIR=$(mktemp -d)
+	echo "GitHub Codespaces environment detected, using $CONTAINER_MOUNT_DIR for container mount"
+elif [[ $(is_overlay_mount /var/lib) == true ]]; then
+	if [[ $(is_overlay_mount /tmp) == false ]]; then
```
Comment (calebbrown) [inline scripts/run_analysis.sh:140]: It might be worth double checking if `/tmp` is `tmpfs` in this case. `tmpfs` memory backed, so loading it up with images is not ideal.

Comment (maxfisher-g) [reply scripts/run_analysis.sh:140]: Fair point, I'll make a fix

**Review by calebbrown — APPROVED** [review]
Looks great!
